/*
 * Copyright 2022 [TronIDE]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import React, { Component } from "react";
import "./index.css";
import CommonModal from "../common/Modal";

let data = [
  {
    key: "You will need a valid API Key.",
    icon: "🔑",
  },
  {
    key: "For privacy reasons, TRON IDE does not upload or store your API Key.",
    icon: "🔒",
  },
  {
    key: "The answers are generated by an AI, not by TRON IDE. Therefore, the platform doesn't assure their accuracy.",
    icon: "🤖️",
  },
  {
    key: "It's recommended that you use the AI-generated answers as reference only.",
    icon: "⚠️",
  },
];

class UsageIntroductionModal extends Component {
  onClose = () => {
    const {onClose}=this.props;
    onClose&&onClose();
  };

  iUnderstandHandle = () => {
    const {onIUnderstand}=this.props;
    onIUnderstand&&onIUnderstand();
  }

  render() {
    return (
      <CommonModal className="usage-introduction-modal" closeIconClass={'usage-introduction-close'} onCancel={this.onClose} getContainer={()=>document.getElementById('ai-panel')}>
        <div className="modal-content-wrapper">
          <h3>Welcome to TRON IDE AI Assistant</h3>
          <div className="content-wrapper">
            {data.map((item,i) => {
              return (
                <div className="item flex-start" key={i}>
                  <div className="tron-icon-wrapper">{item.icon}</div>
                  <span className="text">{item.key}</span>
                </div>
              );
            })}
          </div>
          <div className="btns-wrapper">
            <button onClick={this.iUnderstandHandle}>I Understand</button>
          </div>
        </div>
      </CommonModal>
    );
  }
}

export default UsageIntroductionModal
